version: '3.9'

services:
  app:
    image: "app"
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #   - .:/app
    ports:
      - 8000:8000
    environment:
      -  DB_HOST=db
      -  DB_NAME=test_db
      -  DB_USER=root
      -  DB_PASS=root
      # -  CHOKIDAR_USEPOLLING=true

    depends_on:
      - db
    command: >
        sh -c "
          python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000
        "
    env_file:
        .env

  db:
    image: "postgres:10"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    ports: 
    - "5432:5432"